import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'



export const metadata: Metadata = {
  title: "Pluto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   
      <html lang="en" suppressHydrationWarning>
        <body>
            {children}
        </body>
      </html>
    
  )
}
